//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M.U.N_System_BackEnd.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"E:\\University\\Year 2\\IMAT2204 - Pro" +
            "ject Management And Development\\M.U.N System\\Database\\Appointment Database.mdf\";" +
            "Integrated Security=True;Connect Timeout=30")]
        public string Appointment_DatabaseConnectionString {
            get {
                return ((string)(this["Appointment_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"|DataDirectory|\\Appointment Databas" +
            "e.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string Appointment_DatabaseConnectionString1 {
            get {
                return ((string)(this["Appointment_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\p14177216\\Source\\Repos\\Proj" +
            "ectManagement\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout=" +
            "30")]
        public string OurDatabaseConnectionString {
            get {
                return ((string)(this["OurDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Chavda_2\\Source\\Repos\\Proje" +
            "ctManagement3\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout=" +
            "30")]
        public string OurDatabaseConnectionString1 {
            get {
                return ((string)(this["OurDatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Chavda_2\\Source\\Repos\\Proje" +
            "ctManagement\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout=3" +
            "0")]
        public string OurDatabaseConnectionString2 {
            get {
                return ((string)(this["OurDatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Chavda_2\\Source\\Repos\\Proje" +
            "ctManagement2\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout=" +
            "30")]
        public string OurDatabaseConnectionString3 {
            get {
                return ((string)(this["OurDatabaseConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\UwaisAkbar\\Source\\Repos\\Pro" +
            "jectManagement\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout" +
            "=30")]
        public string OurDatabaseConnectionString44 {
            get {
                return ((string)(this["OurDatabaseConnectionString44"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\OurDatabase.mdf;Inte" +
            "grated Security=True;Connect Timeout=30")]
        public string OurDatabaseConnectionString4 {
            get {
                return ((string)(this["OurDatabaseConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\UwaisAkbar\\Source\\Repos\\Pro" +
            "jectManagement4\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeou" +
            "t=30")]
        public string OurDatabaseConnectionString5 {
            get {
                return ((string)(this["OurDatabaseConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Chavda_2\\Source\\Repos\\Proje" +
            "ctManagement4\\App_Data\\OurDatabase.mdf;Integrated Security=True;Connect Timeout=" +
            "30")]
        public string OurDatabaseConnectionString6 {
            get {
                return ((string)(this["OurDatabaseConnectionString6"]));
            }
        }
    }
}
